language: julia

if: branch=master

notifications:
  email: false

os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
stages:
  - build
  - coverage
  - documentation

jobs:
  allow_failures:
    julia: nightly
<<<<<<< HEAD
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
=======
  include:
    - stage: build
      julia: 1.0
      os: linux
    - stage: coverage
      julia: 1.0
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
      after_success: skip
    - stage: documentation
>>>>>>> 15ea786... Update to Travis staged build.
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
